# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

ARG PYTHON_VERSION=3.10-slim-bullseye

FROM python:$PYTHON_VERSION

ARG DAGSTER_VERSION=1.3.6
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

# TODO: Add --no-cache-dir to reduce image size
RUN pip install \
    dagster==$DAGSTER_VERSION \
    dagster-graphql \
    dagit \
    dagster-postgres
    # dagster-docker

WORKDIR $DAGSTER_HOME
COPY dagster.yaml workspace.yaml ./
